### Тема “Вычисления с помощью Numpy”

### Задание 1


In [ ]:
import numpy as np

In [6]:
a = np.array([[1,6],
            [2,8],
            [3,11],
            [3,10],
            [1,7]])
a


array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [15]:
a_trans = np.transpose(a)
mean_a = np.array([np.mean(a_trans[0]), np.mean(a_trans[1])])
mean_a

array([2. , 8.4])

### Задание 2

In [16]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [46]:
a_trans_centered = np.transpose(a_centered)

a_centered_sp = a_trans_centered[0].dot(a_trans_centered[1])

covariance = a_centered_sp / (a.shape[0] - 1)
covariance


2.0

### Задание 4

In [43]:
np.cov(np.transpose(a))[0, 1]

2.0

### Тема “Работа с данными в Pandas”

Задание 1

In [47]:
import pandas as pd

In [80]:
dict1 = {
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
}

authors = pd.DataFrame(dict1)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [81]:
dict2 = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
}

book = pd.DataFrame(dict2)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

In [82]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [83]:
authors_price.sort_values(by="price", inplace=True)
top5 = authors_price.tail(5)
top5

author_id author_name         book_title  price
2          1    Тургенев  Дворянское гнездо    350
5          3  Островский              Гроза    370
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
3          2       Чехов   Толстый и тонкий    500

Задание 4

In [88]:
authors_stat = authors_price.copy()
authors_stat["min_price"] = authors_stat["price"]
authors_stat["max_price"] = authors_stat["price"]
authors_stat["mean_price"] = authors_stat["price"]
groupby = authors_stat.groupby("author_name")

authors_stat =groupby.agg({"min_price": "min", "max_price": "max", "mean_price": "mean"})
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000